In [84]:
person = {
    "first": "Corey",
    "last": "Schafer",
    "email": "CoreyMSchafer@gmail.com"
}

In [85]:
people = {
    "first": ["Corey"],
    "last": ["Schafer"],
    "email": ["CoreyMSchafer@gmail.com"]
}

In [86]:
people = {
    "first": ["Corey", 'Jane', 'john'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@email.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [87]:
people['email']

['CoreyMSchafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [165]:
import pandas as pd
import numpy as np

In [89]:
df = pd.DataFrame(people)

In [90]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
1   Jane      Doe        JaneDoe@email.com
2   john      Doe        JohnDoe@email.com

In [91]:
df['email']

0    CoreyMSchafer@email.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [92]:
type(df['email'])

pandas.core.series.Series

In [93]:
df.email

0    CoreyMSchafer@email.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [94]:
 df[['last', 'email']]

      last                    email
0  Schafer  CoreyMSchafer@email.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [95]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [96]:
df.iloc[[0, 1], [1, 2, 0]]

      last                    email  first
0  Schafer  CoreyMSchafer@email.com  Corey
1      Doe        JaneDoe@email.com   Jane

In [97]:
df.loc[[0, 1], ['email', 'last']]

                     email     last
0  CoreyMSchafer@email.com  Schafer
1        JaneDoe@email.com      Doe

In [98]:
df['email']

0    CoreyMSchafer@email.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [99]:
df.set_index('email', inplace=True)

In [100]:
df

                         first     last
email
CoreyMSchafer@email.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         john      Doe

In [101]:
df.index

Index(['CoreyMSchafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='object', name='email')

In [102]:
df.reset_index(inplace=True)
df

                     email  first     last
0  CoreyMSchafer@email.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   john      Doe

In [103]:
filtt = (df['last'] == 'Doe')

In [104]:
df[filtt]

               email first last
1  JaneDoe@email.com  Jane  Doe
2  JohnDoe@email.com  john  Doe

In [105]:
filt = (df['last'] == 'Schafer') | (df['first'] == 'john' )

In [106]:
df.loc[-filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: object

In [107]:
df.columns = ['email', 'first_name', 'last_name']

In [108]:
df.columns

Index(['email', 'first_name', 'last_name'], dtype='object')

In [109]:
df.columns = [x.upper() for x in df.columns]
df

                     EMAIL FIRST_NAME LAST_NAME
0  CoreyMSchafer@email.com      Corey   Schafer
1        JaneDoe@email.com       Jane       Doe
2        JohnDoe@email.com       john       Doe

In [110]:
df.columns = df.columns.str.replace(' ', '_')
df

                     EMAIL FIRST_NAME LAST_NAME
0  CoreyMSchafer@email.com      Corey   Schafer
1        JaneDoe@email.com       Jane       Doe
2        JohnDoe@email.com       john       Doe

In [111]:
df.rename(columns={'FIRST_NAME': 'FIRST', 'LAST_NAME':'LAST'}, inplace=True)

In [112]:
df

                     EMAIL  FIRST     LAST
0  CoreyMSchafer@email.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   john      Doe

In [113]:
df.loc[2] = ['JohnSmith@gmail.com','John', 'Smith']

In [114]:
df.loc[2, ['EMAIL','LAST']] = ['JohnDoe@gmail.com','Doe']

In [115]:
df

                     EMAIL  FIRST     LAST
0  CoreyMSchafer@email.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@gmail.com   John      Doe

In [116]:
 df.at[2,'EMAIL'] = 'johnDoe@gmail.com'

In [117]:
df

                     EMAIL  FIRST     LAST
0  CoreyMSchafer@email.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        johnDoe@gmail.com   John      Doe

In [118]:
df['EMAIL'] = df['EMAIL'].str.lower()

In [119]:
df

                     EMAIL  FIRST     LAST
0  coreymschafer@email.com  Corey  Schafer
1        janedoe@email.com   Jane      Doe
2        johndoe@gmail.com   John      Doe

In [120]:
df['EMAIL'].apply(len)

0    23
1    17
2    17
Name: EMAIL, dtype: int64

In [121]:
def update_email(EMAIL):
    return EMAIL.upper()

In [122]:
df['EMAIL'].apply(update_email)

0    COREYMSCHAFER@EMAIL.COM
1          JANEDOE@EMAIL.COM
2          JOHNDOE@GMAIL.COM
Name: EMAIL, dtype: object

In [123]:
df['EMAIL'] = df['EMAIL'].apply(update_email)

In [124]:
df

                     EMAIL  FIRST     LAST
0  COREYMSCHAFER@EMAIL.COM  Corey  Schafer
1        JANEDOE@EMAIL.COM   Jane      Doe
2        JOHNDOE@GMAIL.COM   John      Doe

In [125]:
df['EMAIL'] = df['EMAIL'].apply(lambda x: x.lower())

In [126]:
df

                     EMAIL  FIRST     LAST
0  coreymschafer@email.com  Corey  Schafer
1        janedoe@email.com   Jane      Doe
2        johndoe@gmail.com   John      Doe

In [127]:
df.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [128]:
len(df['EMAIL'])

3

In [129]:
df.apply(pd.Series.min)

EMAIL    coreymschafer@email.com
FIRST                      Corey
LAST                         Doe
dtype: object

In [130]:
df.apply(lambda x: x.min())

EMAIL    coreymschafer@email.com
FIRST                      Corey
LAST                         Doe
dtype: object

In [131]:
df.applymap(len)

C:\Users\tanis\AppData\Local\Temp\ipykernel_14744\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   EMAIL  FIRST  LAST
0     23      5     7
1     17      4     3
2     17      4     3

In [132]:
df.applymap(str.lower)

C:\Users\tanis\AppData\Local\Temp\ipykernel_14744\357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

                     EMAIL  FIRST     LAST
0  coreymschafer@email.com  corey  schafer
1        janedoe@email.com   jane      doe
2        johndoe@gmail.com   john      doe

In [133]:
df['FIRST'].map({'Corey': 'Chris', 'Jane': 'Mary'})

0    Chris
1     Mary
2      NaN
Name: FIRST, dtype: object

In [134]:
df['FIRST'] = df['FIRST'].replace({'Corey': 'Chris', 'Jane': 'Mary'})
df

                     EMAIL  FIRST     LAST
0  coreymschafer@email.com  Chris  Schafer
1        janedoe@email.com   Mary      Doe
2        johndoe@gmail.com   John      Doe

In [135]:
 df['FIRST'] + ' ' + df['LAST']

0    Chris Schafer
1         Mary Doe
2         John Doe
dtype: object

In [136]:
df['FULL_NAME'] = df['FIRST'] + ' ' + df['LAST']
df

                     EMAIL  FIRST     LAST      FULL_NAME
0  coreymschafer@email.com  Chris  Schafer  Chris Schafer
1        janedoe@email.com   Mary      Doe       Mary Doe
2        johndoe@gmail.com   John      Doe       John Doe

In [137]:
df.drop(columns= ['FIRST', 'LAST'], inplace=True)
df

                     EMAIL      FULL_NAME
0  coreymschafer@email.com  Chris Schafer
1        janedoe@email.com       Mary Doe
2        johndoe@gmail.com       John Doe

In [138]:
df['FULL_NAME'].str.split(' ', expand=True)

       0        1
0  Chris  Schafer
1   Mary      Doe
2   John      Doe

In [139]:
df[['FIRST', 'LAST']] = df['FULL_NAME'].str.split(' ', expand=True)
df

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
1        janedoe@email.com       Mary Doe   Mary      Doe
2        johndoe@gmail.com       John Doe   John      Doe

In [140]:
people2 = {
    "FIRST": ["Tony", 'Steve'],
    "LAST": ["Stark", 'Rogers'],
    "EMAIL": ["TronMan@avenge.com", 'Cap@avenge.com']
}
df2 = pd.DataFrame(people2)
df['FULL_NAME'] = df['FIRST'] + ' ' + df['LAST']

In [141]:
df2

   FIRST    LAST               EMAIL
0   Tony   Stark  TronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [142]:
df3 = pd.concat([df, df2], ignore_index=True).drop_duplicates()
df3.head()

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
1        janedoe@email.com       Mary Doe   Mary      Doe
2        johndoe@gmail.com       John Doe   John      Doe
3       TronMan@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [143]:
df3.drop(index=4)

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
1        janedoe@email.com       Mary Doe   Mary      Doe
2        johndoe@gmail.com       John Doe   John      Doe
3       TronMan@avenge.com            NaN   Tony    Stark

In [144]:
filt = df3['LAST'] == 'Doe'
df3.drop(index=df3[filt].index)

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
3       TronMan@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [145]:
df.sort_values(by='LAST', ascending=False)

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
1        janedoe@email.com       Mary Doe   Mary      Doe
2        johndoe@gmail.com       John Doe   John      Doe

In [146]:
df.sort_values(by=['LAST', 'FIRST'], ascending=True)

                     EMAIL      FULL_NAME  FIRST     LAST
2        johndoe@gmail.com       John Doe   John      Doe
1        janedoe@email.com       Mary Doe   Mary      Doe
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer

In [147]:
df.sort_index()

                     EMAIL      FULL_NAME  FIRST     LAST
0  coreymschafer@email.com  Chris Schafer  Chris  Schafer
1        janedoe@email.com       Mary Doe   Mary      Doe
2        johndoe@gmail.com       John Doe   John      Doe

In [148]:
df['LAST'].sort_values()

1        Doe
2        Doe
0    Schafer
Name: LAST, dtype: object

In [161]:
persons = {
    'first' : ['Tani', 'Priyank', 'NA', None],
    'last' : ['Khaneja', 'Sachdeva', 'Missing', None],
    'email' : ['tanikhaneja@gmail.com', 'priyanksachdeva@gmail.com','Missing', None],
    'age' : ['33', '55', '63', None]
}

In [167]:
df2 = pd.DataFrame(persons)

df2.replace('NA', np.nan, inplace=True)
df2.replace('Missing', np.nan, inplace=True)
df2

     first      last                      email   age
0     Tani   Khaneja      tanikhaneja@gmail.com    33
1  Priyank  Sachdeva  priyanksachdeva@gmail.com    55
2      NaN       NaN                        NaN    63
3     None      None                       None  None

In [168]:
df2.dropna(axis='index', how='any')

     first      last                      email age
0     Tani   Khaneja      tanikhaneja@gmail.com  33
1  Priyank  Sachdeva  priyanksachdeva@gmail.com  55

In [169]:
df2.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2   True   True   True  False
3   True   True   True   True

In [170]:
df2.fillna('MISSING')

     first      last                      email      age
0     Tani   Khaneja      tanikhaneja@gmail.com       33
1  Priyank  Sachdeva  priyanksachdeva@gmail.com       55
2  MISSING   MISSING                    MISSING       63
3  MISSING   MISSING                    MISSING  MISSING

In [171]:
df2.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [173]:
df2['age'] = df2['age'].astype(float)

In [174]:
df2.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [175]:
df2['age'].mean()

np.float64(50.333333333333336)